### ISSUE TITLE
Use sparse Matrix to optimize Memory errors

### ISSUE THREAD

**Issue by mostafa-mahmoud** [mostafa-mahmoud/sahwaka#13]

**Comment by ndomar** [comment]
What type of memory errors are you getting?

**Comment by mostafa-mahmoud** [comment]
Not any more, do you think we can use the sparse Matrix or will it screw up stuff? (If it's a lot of work to change, just close the issue)

**Comment by ndomar** [comment]
@mostafa-mahmoud I didn't try but I think it won't screw up stuff, we can leave this issue here and try to migrate if we hav time.

**Comment by mostafa-mahmoud** [comment]
@ndomar Should we close this since we tried them and it was slow?

**Comment by mostafa-mahmoud** [comment]
We tried it and it was slower.
