### ISSUE TITLE
Extra database parameters in runnables

### ISSUE THREAD

**Issue by ndomar** [mostafa-mahmoud/sahwaka#15]
I have a problem with this parameter being there, I realize for test reasons you need to initialize some abstracts. The correct way to do it is to mock the dataparser and make it return some random abstracts.

**Comment by mostafa-mahmoud** [comment]
@ndomar Do you think it will benefit us at all generating random data? because we will never know from it if we made good/bad recommendations, so I suggest that we just close this issue.

**Comment by ndomar** [comment]
@mostafa-mahmoud My argument is not whether it will benefit us or not. My argument is that the variable is there only for test reasons. You only need it to be able to run the lda method without using the data processor to see whether it is working or not and to avoid wasting a lot of time. that's why I don't see why it is in the runnables. As I said, I would rather have it in a test case as a mocked method. It doesn't seem like a right design approach for me.

**Comment by mostafa-mahmoud** [comment]
I get your point, but the main point of the module is to run things, I expect this module to have all facilities to run our algorithms and observe some results. (Sometimes we want to run with small content data to make sure the output is corresponding to something that we expect,and also to see if it makes sense, Tests won't help us to see this. And also before big runs, it would be nice to make small runs to see that the exact configuration is working correctly)
