### ISSUE TITLE
TopRecommendations optimization

### ISSUE THREAD

**Issue by mostafa-mahmoud** [mostafa-mahmoud/sahwaka#18]
Make sure the TopRecommendations data structure is optimized and tested, that it maybe exported later on.

**Comment by ndomar** [comment]
@mostafa-mahmoud I don't get what you mean by "export later on"

**Comment by mostafa-mahmoud** [comment]
I meant if someone wanted to use it later in a separate project, then they can easily export your module, and it would be simple and optimized for such a purpose.
