### ISSUE TITLE
Abstracts analyzer for LDA and LDA2Vec

### ISSUE THREAD

**Issue by mostafa-mahmoud** [mostafa-mahmoud/sahwaka#23]
Add a module to compute abstracts-related stuff, like count vectors and so on.

**Comment by mostafa-mahmoud** [comment]
@ndomar 

I need the following fetchers here:
[(article_id, word_id) for article_id for word_id]  (a flat list of pairs, sorted lexicographically)
[(word_id, word_count) for word_id] (where word_count is the count over all the articles, sorted by word_id)
[(article_id, word_id, word_count_in_article) for article_id for word_id] (a flat list of triples of article_id, word_id and word_count_in_article; sorted lexicographically)

The second one can be generated from the third I think, if we sum the third over the articles.

**Comment by ndomar** [comment]
@mostafa-mahmoud You don't need the word itself whatsoever?

**Comment by mostafa-mahmoud** [comment]
(forget to mention that the implementation of the first is easily computed from the third)
The current implementation doesn't need them.
