### ISSUE TITLE
LDA CountVectorizer

### ISSUE THREAD

**Issue by mostafa-mahmoud** [mostafa-mahmoud/sahwaka#9]
Recheck if we will need the countVectorizer in the LDA or it can be substituted with the output from DataParser.

**Comment by mostafa-mahmoud** [comment]
Why were you thinking that I'm reinventing the wheel when using the CountVectorizer? So what kind of functionality do we have from the data parser?

**Comment by ndomar** [comment]
My point was we already have the counts in the MySQL table. You can add a function that fetches this data and returns a matrix instead of re-computing it. Also, it would be better to use tf-idf if you would rather use your own implementation

**Comment by mostafa-mahmoud** [comment]
Will be handled in #23
